spring:
  application:
    name: realisasi-pemda-service
  docker:
    compose:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/kertaskerja_realisasi_pemda
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.kertaskerja.local/realms/KabMadiun

server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server: DEBUG
    reactor.netty.http.server: DEBUG
    cc.kertaskerja.integration.penetapan: DEBUG

integration:
  penetapan:
    base-url: https://penetapan-service-staging.zeabur.app
    read-through-enabled: true
    connect-timeout: 5s
    read-timeout: 10s

  upload:
    base-url: https://upload-service-staging.zeabur.app
    connect-timeout: 5s
    read-timeout: 10s

  kepegawaian:
    base-url: https://kepegawaian-service-mahulu-test.zeabur.app
    connect-timeout: 5s
    read-timeout: 10s