spring:
  application:
    name: realisasi-pemda-service
  docker:
    compose:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgresql://localhost:5432/kertaskerja_realisasi_pemda
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/kertaskerja_realisasi_pemda
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.kertaskerja.cc/realms/TestRealm
  output:
    ansi: enabled

server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server: DEBUG
    reactor.netty.http.server: DEBUG
    cc.kertaskerja.integration.penetapan: DEBUG

integration:
  penetapan:
    base-url: ${PENETAPAN_SERVICE_URL}
    read-through-enabled: true
    connect-timeout: 5s
    read-timeout: 10s

  upload:
    base-url: ${UPLOAD_SERVICE_URL}
    read-through-enabled: true
    connect-timeout: 5s
    read-timeout: 10s

  kepegawaian:
    base-url: ${KEPEGAWAIAN_SERVICE_URL}
    read-through-enabled: true
    connect-timeout: 5s
    read-timeout: 10s