ALTER TABLE realisasi_target_renaksi_individu
    ADD COLUMN tahun VARCHAR(10) NOT NULL DEFAULT '',
    ADD COLUMN bulan VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN satuan VARCHAR(255) NOT NULL DEFAULT '%',
    ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'UNCHECKED';
