ALTER TABLE realisasi_target_renaksi_individu
    ADD COLUMN IF NOT EXISTS sasaran VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS renaksi VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS indikator VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target NUMERIC(20, 2) NOT NULL DEFAULT 0;
