name: Build and Push image
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: tests
        run: |
          chmod +x gradlew
          ./gradlew test
